

// ONE FILE PER PROJECT

const commits = [
  { date: Date.UTC(2016, 10, 6, 21, 30), message: 'Translated the first few lines', previous_commit: '', hash: 'Dantecommithash1', committer: 'Bob Williams', projectId: 1 },
  { date: Date.UTC(2016, 10, 6, 22, 28), message: 'Added more lines', previous_commit: 'Dantecommithash1', hash: 'Dantecommithash2', committer: 'Barry Smith', projectId: 1 },
  { date: Date.UTC(2016, 10, 7, 7, 5), message: 'Fixed some of the meter', previous_commit: 'Dantecommithash1', hash: 'Dantecommithash3', committer: 'Bernard Jones', projectId: 1 },
  { date: Date.UTC(2016, 10, 7, 11, 25), message: "Started on Virgil's dialogue", previous_commit: 'Dantecommithash2, Dantecommithash3', hash: 'Dantecommithash4', committer: 'Beatrice Johnson', projectId: 1 },
  { date: Date.UTC(2016, 10, 7, 14), message: 'Added a few stanzas', previous_commit: 'Dantecommithash4', hash: 'Dantecommithash5', committer: 'Billy Browne', projectId: 1 },
  { date: Date.UTC(2016, 10, 8, 16, 21), message: 'Translated lines 58-71', previous_commit: 'Dantecommithash5', hash: 'Dantecommithash6', committer: 'Bella Miller', projectId: 1 },
  { date: Date.UTC(2016, 10, 10, 10, 24), message: 'Almost through the first canto!', previous_commit: 'Dantecommithash7', hash: 'Dantecommithash7', committer: 'Bethany Davis', projectId: 1 },
  { date: Date.UTC(2016, 10, 13, 17, 11), message: 'Started project & invited everyone', previous_commit: '', hash: 'Shakespearecommithash1', committer: 'Billy Browne', projectId: 2 },
  { date: Date.UTC(2016, 10, 14, 12, 14), message: 'Added more lines', previous_commit: 'Shakespearecommithash1', hash: 'Shakespearecommithash2', committer: 'Bella Miller', projectId: 2 },
  { date: Date.UTC(2016, 10, 14, 14, 3), message: 'Changed some word choice', previous_commit: 'Shakespearecommithash2', hash: 'Shakespearecommithash3', committer: 'Bethany Davis', projectId: 2 },
  { date: Date.UTC(2016, 10, 14, 17, 8), message: 'Expanded on his self-doubt', previous_commit: 'Shakespearecommithash3', hash: 'Shakespearecommithash4', committer: 'Brian Taylor', projectId: 2 },
  { date: Date.UTC(2016, 10, 18, 10, 15), message: 'Fixed the meter on line 27', previous_commit: 'Shakespearecommithash4', hash: 'Shakespearecommithash5', committer: 'Bernadette Wilson', projectId: 2 },
  { date: Date.UTC(2016, 10, 18, 13, 17), message: "Ready for Lady's appearance", previous_commit: 'Shakespearecommithash5', hash: 'Shakespearecommithash6', committer: 'Betsy White', projectId: 2 },
  { date: Date.UTC(2016, 10, 19, 8, 12), message: 'Started with Brachnell', previous_commit: '', hash: 'Wildecommithash1', committer: 'Bertha Hill', projectId: 3 },
  { date: Date.UTC(2016, 10, 19, 10, 45), message: 'Made Jack more sympathetic', previous_commit: 'Wildecommithash1', hash: 'Wildecommithash2', committer: 'Brittany Thomas', projectId: 3 },
  { date: Date.UTC(2016, 10, 19, 14, 42), message: 'Improved word choice', previous_commit: 'Wildecommithash2', hash: 'Wildecommithash3', committer: 'Bailey Clark', projectId: 3 },
  { date: Date.UTC(2016, 10, 20, 12, 33), message: 'Ended on Brachnell absurdity', previous_commit: 'Wildecommithash3', hash: 'Wildecommithash4', committer: 'Brooke Jackson', projectId: 3 },
  { date: Date.UTC(2016, 10, 21, 16, 39), message: 'Started with her department', previous_commit: '', hash: 'Sinclaircommithash1', committer: 'Bertha Hill', projectId: 4 },
  { date: Date.UTC(2016, 10, 22, 12, 53), message: 'Expanded rotting meat descriptions', previous_commit: 'Sinclaircommithash1', hash: 'Sinclaircommithash2', committer: 'Brittany Thomas', projectId: 4 },
  { date: Date.UTC(2016, 10, 22, 14, 57), message: 'Fixed some of the grammar', previous_commit: 'Sinclaircommithash2', hash: 'Sinclaircommithash3', committer: 'Bailey Clark', projectId: 4 },
  { date: Date.UTC(2016, 10, 22, 16, 51), message: 'More rotting meat desciptions', previous_commit: 'Sinclaircommithash3', hash: 'Sinclaircommithash4', committer: 'Bailey Clark', projectId: 4 },
  { date: Date.UTC(2016, 10, 23, 10, 47), message: 'Added neighbor characterization', previous_commit: 'Sinclaircommithash4', hash: 'Sinclaircommithash5', committer: 'Bailey Clark', projectId: 4 },
  { date: Date.UTC(2016, 10, 23, 15, 4), message: 'Amplified the poverty', previous_commit: 'Sinclaircommithash5', hash: 'Sinclaircommithash6', committer: 'Brenda Allen', projectId: 4 },
  { date: Date.UTC(2016, 10, 24, 14, 11), message: 'Ended with vivid grave imagery', previous_commit: 'Sinclaircommithash6', hash: 'Sinclaircommithash7', committer: 'Barb Evans', projectId: 4 },
  { date: Date.UTC(2016, 10, 25, 17, 2), message: 'Created project', previous_commit: '', hash: 'Goldingcommithash1', committer: 'Ben Martin', projectId: 5 },
  { date: Date.UTC(2016, 10, 26, 9, 49), message: 'Started with argument about fire', previous_commit: 'Goldingcommithash1', hash: 'Goldingcommithash2', committer: 'Brad Wright', projectId: 5 },
  { date: Date.UTC(2016, 10, 26, 12, 17), message: 'Added mention of the ship', previous_commit: 'Goldingcommithash2', hash: 'Goldingcommithash3', committer: 'Bruce King', projectId: 5 },
  { date: Date.UTC(2016, 10, 26, 14, 4), message: 'Rewrote some dialogue', previous_commit: 'Goldingcommithash3', hash: 'Goldingcommithash4', committer: 'Brett Adams', projectId: 5 },
  { date: Date.UTC(2016, 10, 27, 13, 27), message: 'Wrote the face-off', previous_commit: 'Goldingcommithash4', hash: 'Goldingcommithash5', committer: 'Bertha Hill', projectId: 5 },
  { date: Date.UTC(2016, 10, 28, 19, 46), message: 'Reworded to make animalistic', previous_commit: 'Goldingcommithash5', hash: 'Goldingcommithash6', committer: 'Brittany Thomas', projectId: 5 },
  { date: Date.UTC(2016, 10, 29, 16, 41), message: 'Ends with Jack apologizing', previous_commit: 'Goldingcommithash6', hash: 'Goldingcommithash7', committer: 'Bailey Clark', projectId: 5 },
  { date: Date.UTC(2016, 10, 31, 20, 52), message: 'Started by setting scene', previous_commit: '', hash: 'Conradcommithash1', committer: 'Brooke Jackson', projectId: 6 },
  { date: Date.UTC(2016, 11, 2, 21, 26), message: 'Fixed grammar and expanded', previous_commit: 'Conradcommithash1', hash: 'Conradcommithash2', committer: 'Brenda Allen', projectId: 6 },
  { date: Date.UTC(2016, 11, 3, 18, 29), message: 'Reflecting on Kurtz', previous_commit: 'Conradcommithash2', hash: 'Conradcommithash3', committer: 'Barb Evans', projectId: 6 },
  { date: Date.UTC(2016, 11, 4, 13, 15), message: 'Conversations with Kurtz', previous_commit: 'Conradcommithash3', hash: 'Conradcommithash4', committer: 'Ben Martin', projectId: 6 },
  { date: Date.UTC(2016, 10, 29, 16, 41), message: 'Expanded on questioning', previous_commit: 'Conradcommithash4', hash: 'Conradcommithash5', committer: 'Brad Wright', projectId: 6 },
  { date: Date.UTC(2016, 10, 31, 20, 52), message: 'Added more detail', previous_commit: 'Conradcommithash5', hash: 'Conradcommithash6', committer: 'Bruce King', projectId: 6 },
  { date: Date.UTC(2016, 11, 2, 21, 26), message: 'Edited to make mood darker', previous_commit: 'Conradcommithash6', hash: 'Conradcommithash7', committer: 'Brett Adams', projectId: 6 },
  { date: Date.UTC(2016, 11, 3, 18, 29), message: 'Added Kurtz final moments', previous_commit: 'Conradcommithash7', hash: 'Conradcommithash8', committer: 'Bertha Hill', projectId: 6 },
  { date: Date.UTC(2016, 11, 4, 13, 15), message: 'Ended with self-reflection', previous_commit: 'Conradcommithash8', hash: 'Conradcommithash9', committer: 'Brittany Thomas', projectId: 6 },
  { date: Date.UTC(2016, 11, 2, 21, 26), message: 'Initial start to "Alien". Remember the quotes!', previous_commit: '', hash: 'Aliencommithash1', committer: 'Brett Adams', projectId: 7 },
  { date: Date.UTC(2016, 11, 3, 18, 29), message: 'Deleted some things', previous_commit: 'Aliencommithash1', hash: 'Aliencommithash2', committer: 'Bertha Hill', projectId: 7 },
  { date: Date.UTC(2016, 11, 4, 13, 15), message: 'Title changed from "Alien" to "Alien Waaaars"; possibly better for larger market?', previous_commit: 'Aliencommithash2', hash: 'Aliencommithash3', committer: 'Brittany Thomas', projectId: 7 }
];

// MULTIPLE FILES PER PROJECT

// const commits = [
  // { date: Date.UTC(2016, 10, 6, 21, 30), message: 'Dante1', previous_commit: '', hash: 'thisispoetrycommithashnumber1', committer: '', projectId: 1 },
  // { date: Date.UTC(2016, 10, 6, 22, 28), message: 'Dante2', previous_commit: 'thisispoetrycommithashnumber1', hash: 'thisispoetrycommithashnumber2', projectId: 1 },
  // { date: Date.UTC(2016, 10, 7, 7, 5), message: 'Dante3', previous_commit: 'thisispoetrycommithashnumber1', hash: 'thisispoetrycommithashnumber3', projectId: 1 },
  // { date: Date.UTC(2016, 10, 7, 11, 25), message: 'Dante4', previous_commit: 'thisispoetrycommithashnumber2, thisispoetrycommithashnumber3', hash: 'thisispoetrycommithashnumber4', projectId: 1 },
  // { date: Date.UTC(2016, 10, 7, 14), message: 'Dante5', previous_commit: 'thisispoetrycommithashnumber4', hash: 'thisispoetrycommithashnumber5', projectId: 1 },
  // { date: Date.UTC(2016, 10, 8, 16, 21), message: 'Dante6', previous_commit: 'thisispoetrycommithashnumber5', hash: 'thisispoetrycommithashnumber6', projectId: 1 },
  // { date: Date.UTC(2016, 10, 10, 10, 24), message: 'Dante7', previous_commit: 'thisispoetrycommithashnumber7', hash: 'thisispoetrycommithashnumber7', projectId: 1 },
  // { date: Date.UTC(2016, 10, 13, 17, 11), message: 'Shakespeare1', previous_commit: '', hash: 'thisisplaycommithashnumber1', projectId: 2 },
  // { date: Date.UTC(2016, 10, 14, 12, 14), message: 'Wilde1', previous_commit: 'thisisplaycommithashnumber1', hash: 'thisisplaycommithashnumber2', projectId: 2 },
  // { date: Date.UTC(2016, 10, 14, 14, 3), message: 'Shakespeare2', previous_commit: 'thisisplaycommithashnumber2', hash: 'thisisplaycommithashnumber3', projectId: 2 },
  // { date: Date.UTC(2016, 10, 14, 17, 8), message: 'Shakespeare3', previous_commit: 'thisisplaycommithashnumber3', hash: 'thisisplaycommithashnumber4', projectId: 2 },
  // { date: Date.UTC(2016, 10, 18, 10, 15), message: 'Shakespeare4', previous_commit: 'thisisplaycommithashnumber4', hash: 'thisisplaycommithashnumber5', projectId: 2 },
  // { date: Date.UTC(2016, 10, 18, 13, 17), message: 'Shakespeare5', previous_commit: 'thisisplaycommithashnumber5', hash: 'thisisplaycommithashnumber6', projectId: 2 },
  // { date: Date.UTC(2016, 10, 19, 8, 12), message: 'Wilde2', previous_commit: 'thisisplaycommithashnumber6', hash: 'thisisplaycommithashnumber7', projectId: 2 },
  // { date: Date.UTC(2016, 10, 19, 10, 45), message: 'Wilde3', previous_commit: 'thisisplaycommithashnumber7', hash: 'thisisplaycommithashnumber8', projectId: 2 },
  // { date: Date.UTC(2016, 10, 19, 14, 42), message: 'Shakespeare6', previous_commit: 'thisisplaycommithashnumber8', hash: 'thisisplaycommithashnumber9', projectId: 2 },
  // { date: Date.UTC(2016, 10, 20, 12, 33), message: 'Wilde4', previous_commit: 'thisisplaycommithashnumber9', hash: 'thisisplaycommithashnumber10', projectId: 2 },
  // { date: Date.UTC(2016, 10, 21, 16, 39), message: 'Sinclair1', previous_commit: '', hash: 'thisisnovelcommitnumber1', projectId: 3 },
  // { date: Date.UTC(2016, 10, 22, 12, 53), message: 'Golding1', previous_commit: 'thisisnovelcommitnumber1', hash: 'thisisnovelcommitnumber2', projectId: 3 },
  // { date: Date.UTC(2016, 10, 22, 14, 57), message: 'Sinclair2', previous_commit: 'thisisnovelcommitnumber2', hash: 'thisisnovelcommitnumber3', projectId: 3 },
  // { date: Date.UTC(2016, 10, 22, 16, 51), message: 'Conrad1', previous_commit: 'thisisnovelcommitnumber3', hash: 'thisisnovelcommitnumber4', projectId: 3 },
  // { date: Date.UTC(2016, 10, 23, 10, 47), message: 'Sinclair3', previous_commit: 'thisisnovelcommitnumber4', hash: 'thisisnovelcommitnumber5', projectId: 3 },
  // { date: Date.UTC(2016, 10, 23, 15, 4), message: 'Golding2', previous_commit: 'thisisnovelcommitnumber5', hash: 'thisisnovelcommitnumber6', projectId: 3 },
  // { date: Date.UTC(2016, 10, 24, 14, 11), message: 'Golding3', previous_commit: 'thisisnovelcommitnumber6', hash: 'thisisnovelcommitnumber7', projectId: 3 },
  // { date: Date.UTC(2016, 10, 25, 17, 2), message: 'Conrad2', previous_commit: 'thisisnovelcommitnumber7', hash: 'thisisnovelcommitnumber8', projectId: 3 },
  // { date: Date.UTC(2016, 10, 26, 9, 49), message: 'Sinclair4', previous_commit: 'thisisnovelcommitnumber8', hash: 'thisisnovelcommitnumber9', projectId: 3 },
  // { date: Date.UTC(2016, 10, 26, 12, 17), message: 'Conrad3', previous_commit: 'thisisnovelcommitnumber9', hash: 'thisisnovelcommitnumber10', projectId: 3 },
  // { date: Date.UTC(2016, 10, 26, 14, 4), message: 'Conrad4', previous_commit: 'thisisnovelcommitnumber10', hash: 'thisisnovelcommitnumber11', projectId: 3 },
  // { date: Date.UTC(2016, 10, 27, 13, 27), message: 'Conrad5', previous_commit: 'thisisnovelcommitnumber11', hash: 'thisisnovelcommitnumber12', projectId: 3 },
  // { date: Date.UTC(2016, 10, 28, 19, 46), message: 'Golding4', previous_commit: 'thisisnovelcommitnumber12', hash: 'thisisnovelcommitnumber13', projectId: 3 },
  // { date: Date.UTC(2016, 10, 29, 16, 41), message: 'Golding5', previous_commit: 'thisisnovelcommitnumber13', hash: 'thisisnovelcommitnumber14', projectId: 3 },
  // { date: Date.UTC(2016, 10, 31, 20, 52), message: 'Conrad6', previous_commit: 'thisisnovelcommitnumber14', hash: 'thisisnovelcommitnumber15', projectId: 3 },
  // { date: Date.UTC(2016, 11, 2, 21, 26), message: 'Sinclair5', previous_commit: 'thisisnovelcommitnumber15', hash: 'thisisnovelcommitnumber16', projectId: 3 },
  // { date: Date.UTC(2016, 11, 3, 18, 29), message: 'Golding6', previous_commit: 'thisisnovelcommitnumber16', hash: 'thisisnovelcommitnumber17', projectId: 3 },
  // { date: Date.UTC(2016, 11, 4, 13, 15), message: 'Conrad7', previous_commit: 'thisisnovelcommitnumber17', hash: 'thisisnovelcommitnumber18', projectId: 3 },
  // { date: Date.UTC(2016, 10, 29, 16, 41), message: 'Sinclair6', previous_commit: 'thisisnovelcommitnumber18', hash: 'thisisnovelcommitnumber19', projectId: 3 },
  // { date: Date.UTC(2016, 10, 31, 20, 52), message: 'Sinclair7', previous_commit: 'thisisnovelcommitnumber19', hash: 'thisisnovelcommitnumber20', projectId: 3 },
  // { date: Date.UTC(2016, 11, 2, 21, 26), message: 'Conrad8', previous_commit: 'thisisnovelcommitnumber20', hash: 'thisisnovelcommitnumber21', projectId: 3 },
  // { date: Date.UTC(2016, 11, 3, 18, 29), message: 'Golding7', previous_commit: 'thisisnovelcommitnumber21', hash: 'thisisnovelcommitnumber22', projectId: 3 },
  // { date: Date.UTC(2016, 11, 4, 13, 15), message: 'Conrad9', previous_commit: 'thisisnovelcommitnumber22', hash: 'thisisnovelcommitnumber23', projectId: 3 }
// ];


module.exports = commits;
